services:
  app:
    build:
      context: . # Set the build context to the current directory
      args:
        - DEV=true

    ports:
      - "8001:8001" # Maps port 8001 from container to host

    volumes:
      - ./app:/app # Syncs local "app" folder with the container

    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8001"
